#!/usr/bin/env bash

# Generates color previews of /assets/assets/css/<color>.css in /previews/<color>.html

color_default="_default-html"
preview_index="generated-preview-pages"
previews_dir="generated-preview-pages"
css_dir="../assets/assets/css"
declare -A meta_css
meta_css=(["_default-html"]=1 ["black-white"]=1 ["base-color"]=1)

mkdir -p "${previews_dir}"

echo "==> Creating preview pages in ${previews_dir}..."

cat > "${preview_index}.html" << END
---
title: "Generated Previews"
description: "Generated Previews from assets/assets/css"
icon: 🔍
permalink: /${preview_index}
sitemap:
  disable: true
theme_color: ${color_default}
---
<p>Here are some saturated colors derived from <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/named-color">named HTML colors</a> (and a sneaked in hex color), some of which work out okay.</p>

<p>As they are generated by <code>generate-previews.sh</code> from the CSS files in <code>assets/assets/css</code>, adding or deleting some will change the available previews.</p>

<p>The CSS code with black and white linking is pretty simple. Here is darkorange:</p>

<pre>
@import "black-white";

:root {
  --bg-color: hsl(33, 100%, 50%);
  --pre-bg-color: hsl(33, 100%, 45%);
}

::selection {
  background-color: var(--link-color);
  color: var(--h-color);
}
</pre>

The CSS build process is quite modular. Each color CSS includes three others: <code>black-white</code>, <code>main</code>, and <code>base</code>. All CSS is classless.

<h2>Previews</h2>

<style>
p.preview {
  padding: 2em;
}

a.preview {
  font-size: 27px;
  font-weight: bold;
}

@media (max-width: 500px) {
  p.preview {
    padding: 1em;
  }

  a.preview {
    font-size: 18px;
  }
}
</style>

END

preview_body=$(cat markdown-to-html-test.html)

shopt -s nullglob
for color in "${css_dir}"/*.css; do
  # Remove leading ${css_dir}/
  color=${color#*"${css_dir}"/}
  # Remove trailing .css
  color=${color%.*}

  if [[ -n "${meta_css[${color}]}" ]]; then
    continue
  fi

  if [[ ${color} == "white" ]]; then
    p_color="black"
    a_color="hsl(92, 47%, 62%)"
    td_color="hsl(31, 29%, 52%)"
  elif [[ ${color} == "black" || ${color} == "grey" ]]; then
    p_color="white"
    a_color="hsl(92, 47%, 62%)"
    td_color="hsl(31, 29%, 52%)"
  else
    p_color="black"
    a_color="white"
    td_color="white"
  fi

  # Quick and dirty hack for hex colors
  if [[ ${color} == "8cbfd8" ]]; then
    echo "<p class=\"preview\" style=\"background-color: #${color}; color: ${p_color};\"><a class=\"preview\" style=\"color: ${a_color}; text-decoration-color: ${td_color};\" href=\"/${previews_dir}/${color}\">#${color}</a> as background color.</p>" >> "${preview_index}.html"
  else
    echo "<p class=\"preview\" style=\"background-color: ${color}; color: ${p_color};\"><a class=\"preview\" style=\"color: ${a_color}; text-decoration-color: ${td_color};\" href=\"/${previews_dir}/${color}\">${color}</a> as background color.</p>" >> "${preview_index}.html"
  fi

  cat > "${previews_dir}/${color}.html" << END
---
title: ${color}
description: "A preview of ${color}"
icon: 🔬
permalink: /${previews_dir}/${color}
sitemap:
  disable: true
theme_color: ${color}
---
END

  echo "${preview_body}" >> "${previews_dir}/${color}.html"
done
shopt -u nullglob

echo "==> Creating preview pages for special case no theme in ${previews_dir}..."

echo "<p class=\"preview\" style=\"background-color: white; color: black;\"><a class=\"preview\" style=\"color: rgb(0, 0, 238); text-decoration-color: rgb(0, 0, 238);\" href=\"/${previews_dir}/no-theme\">no theme</a> without any styling.</p>" >> "${preview_index}.html"

cat > "${previews_dir}/no-theme.html" << END
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>No Theme</title>
</head>
<body>
END

echo "${preview_body}" >> "${previews_dir}/no-theme.html"

cat >> "${previews_dir}/no-theme.html" << END
</body>
</html>
END

echo "==> Generated the following preview pages in ${previews_dir}"

ls "${previews_dir}"
