# CHANGE THIS means the user needs to configure this in the site's hugo.toml

baseURL = 'https://hugo-theme-emojification.michaelnordmeyer.com/' # CHANGE THIS
# cleanDestinationDir = true
copyright = 'Copyright © Michael Nordmeyer' # CHANGE THIS
disableAliases = true
disableHugoGeneratorInject = true # Inserted only on the homepage, see param.disable_hugo_generator_inject
disableKinds = ['404', 'rss'] # 404, home, page, robotstxt, rss, section, sitemap, taxonomy, or term
# enableEmoji = true # https://gohugo.io/quick-reference/emojis/
# enableGitInfo = true # https://gohugo.io/methods/page/gitinfo/ the last modification date for each content page will be the Author Date of the last commit for that file
enableRobotsTXT = true
# ignoreFiles = ['']
locale = 'en-US' # CHANGE THIS
# If mainSections is not defined in the site configuration, this method returns a slice with one element: the top-level section with the most pages.
# mainSections = ['books', 'films'] # https://gohugo.io/methods/site/mainsections/
# panicOnWarning = true
printI18nWarnings = true
printPathWarnings = true
publishDir = 'public'
refLinksErrorLevel = 'WARNING'
titleCaseStyle = 'chicago'
theme = 'hugo-theme-emojification'
themesDir = "../../"
timeZone = 'Europe/Berlin' # CHANGE THIS
title = 'Hugo Theme Emojification' # CHANGE THIS

[params] # https://gohugo.io/configuration/params/
  disable_hugo_generator_inject = true # Replaces Hugo's disableHugoGeneratorInject (set it to true). Applies to all pages and Atom feed
  fediverse_creator = '@mnordmeyer@indieweb.social' # CHANGE THIS # "@username@fediverse.example"
  icon = '🌳' # Can be declared in front matter as well
  lazy_load = true
  license_link = 'https://github.com/michaelnordmeyer/hugo-theme-emojification/blob/main/LICENSE' # CHANGE THIS
  # show_descriptions is used to enable descriptions on pages and index pages like home and categories
  show_descriptions = true
  subtitle = 'A simple and minimal single-author theme with configurable big emoji as the header link, and configurable background colors, which can be chosen for each post or page' # CHANGE THIS # Used for Atom feed, SEO, and web app manifest
  theme_color = 'yellowgreen' # default: none (= no colors. If this CSS file is missing, there will be also no structural styling), and no favicon
  title_separator = ' • '

  [params.atom_feed]
    description_only = false # Can be declared in front matter as well
    filename = 'feed.xml'
    markdownify = true
    title_separator = ': '

  [params.author]
    # email = 'email@site.example' # CHANGE THIS
    name = 'Michael Nordmeyer' # CHANGE THIS
    uri = 'https://michaelnordmeyer.com/' # CHANGE THIS

  [params.date_formats]
    # iso8601 = '2006-01-02T15:04:05Z'
    iso8601 = '2006-01-02T15:04:05-07:00'
    rfc822 = 'Mon, 02 Jan 2006 15:04:05 MST'
    rfc3339 = '2006-01-02T15:04:05-07:00' # Could be called a subset of iso8601

  [[params.socials]] # Social links are used in SEO meta headers
    name = 'GitHub' # CHANGE THIS
    link = 'https://github.com/michaelnordmeyer' # CHANGE THIS

  [[params.socials]] # Social links are used in SEO meta headers
    name = 'LinkedIn' # CHANGE THIS
    link = 'https://www.linkedin.com/in/michaelnordmeyer' # CHANGE THIS

  [[params.socials]] # Social links are used in SEO meta headers
    name = 'XING' # CHANGE THIS
    link = 'https://www.xing.com/profile/Michael_Nordmeyer' # CHANGE THIS

  [[params.socials]] # Social links are used in SEO meta headers
    name = 'Fediverse' # CHANGE THIS
    link = 'https://indieweb.social/@mnordmeyer' # CHANGE THIS

[frontmatter]
  date = ['date', ':filename', 'publishDate', 'pubdate', 'published', 'lastmod', 'modified'] # https://gohugo.io/configuration/front-matter/#dates
  lastmod = ['lastmod', 'modified', 'date', 'publishDate', 'pubdate', 'published', ':git'] # https://gohugo.io/configuration/front-matter/#dates

[markup] # https://gohugo.io/configuration/markup/
  [markup.goldmark]
    # renderer.unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false # Disabled for render-image hook

      [markup.goldmark.parser.attribute]
        block = true # Enabled for render-image hook

    [markup.goldmark.renderer]
      unsafe = true # Allows HTML in Markdown

    [markup.goldmark.extensions]
      strikethrough = false # Needs to be turned off if extras.delete and extras.subscript are enabled

      [markup.goldmark.extensions.extras] # https://gohugo.io/configuration/markup/#extras
        [markup.goldmark.extensions.extras.delete]
          enable = true

        [markup.goldmark.extensions.extras.insert]
          enable = true

        [markup.goldmark.extensions.extras.mark]
          enable = true

        [markup.goldmark.extensions.extras.subscript]
          enable = true

        [markup.goldmark.extensions.extras.superscript]
          enable = true

  [markup.highlight]
    codeFences = false # Toggles highlighting
    guessSyntax = false
    # style = 'monokai' # default: 'monokai'
    tabWidth = 2

  [markup.tableofcontents]
    endlevel = 4
    ordered = false

[minify] # https://gohugo.io/configuration/minify/
  # disableCSS = false
  # disableHTML = false
  # disableJS = false
  # disableJSON = false
  # disableSVG = false
  # disableXML = false
  # minifyOutput = false

[mediatypes] # https://gohugo.io/configuration/media-types/
  [mediatypes.'application/atom+xml']
    suffixes = ['xml']

[menus] # https://gohugo.io/configuration/menus/
  [[menus.main]] # Needed for webmanifest
    name = 'Home' # CHANGE THIS
    pageref = '/'
    weight = 10

[module]
  [module.hugoVersion]
    extended = true # Extended: adds .webp, .scss
    min = "0.146.0"
    # max = "0.199.0"

[outputformats] # https://gohugo.io/configuration/output-formats/
  [outputformats.atom]
    basename = 'feed'
    mediatype = 'application/atom+xml'
    nougly = true

[outputs] # https://gohugo.io/configuration/outputs/
  home = ['html', 'atom'] # Disabled: 'webappmanifest'
  page = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html', 'atom']

[permalinks] # https://gohugo.io/configuration/permalinks/
  [permalinks.page]
    posts = '/:section/:slug/'

  [permalinks.taxonomy]
    categories = "/:title/"
    topics = "/:title/"

  [permalinks.term]
    categories = "/:title/"
    topics = "/:section/:title/"

[privacy] # https://gohugo.io/templates/shortcode/
  [privacy.youtube] # https://gohugo.io/shortcodes/youtube/#privacy
    privacyenhanced = true # www.youtube-nocookie.com

[taxonomies] # https://gohugo.io/content-management/taxonomies/
  category = 'categories'
  tag = 'tags'
